### ISSUE TITLE
Flicker on Scroll

### ISSUE THREAD

**Issue by Georg-code** [AlpsBTE/alpsbte-website#121]
Fix paralax in general

**Comment by b3h3m0th** [comment]
What excactly is the problem?

**Comment by Georg-code** [comment]
![Animation](https://user-images.githubusercontent.com/54809379/133891266-786063ed-ae0f-4d10-bfb8-62ad66939c51.gif)
es

**Comment by b3h3m0th** [comment]
bei mir siehts gut aus. hm

**Comment by Georg-code** [comment]
Was nutzt du für einen Browser? Bei Firefox ist es bei verschiedenen Leuten aufgetreten

**Comment by b3h3m0th** [comment]
chromium. habs gerade im firefox angesehen. kommt ab und zu vor bei mir. find ich echt nicht schlimm. hab auch ehrlich gesagt keine ahnung warum und wie man das fixed.

**Comment by Georg-code** [comment]
Würde erstmal gucken, das der Paralx fluid ist. Kp wie wir das am besten machen, kann ich mir aber angucken und dann das Bild leicht overflowen lassen?

**Comment by b3h3m0th** [comment]
ich sieh den bug nicht mal richtig. ab und zu flickerts im firefox ganz leicht. also kp. find ich wirklich nicht problematisch

**Comment by Georg-code** [comment]
Keine Ahnug, wurde jetzt schon von mehreren angesprochen, dass es stört :/

**Comment by b3h3m0th** [comment]
oh okay ja dann

**Comment by Georg-code** [comment]
Aber ich werde mich drum kümmern, hat keine enorm hohe prio, ist halt ein nice to fix
