### ISSUE TITLE
New font

### ISSUE THREAD

**Issue by NApartas** [AlpsBTE/alpsbte-website#135]
Choose a font style and use it on the whole website.

**Comment by Georg-code** [comment]
What do you mean by "font style"?
The font family, the "boldness", or something else?

**Comment by Georg-code** [comment]
If you mean the font family we will chose probably something from google fonts (cause other fonts are expensive as hell) 
Fonts that will fit good are "DT Sans", "Roboto" or "Poppins". If you like, you can look at them at the official google fonts website.
