### ISSUE TITLE
Implement Routing with lazy loading

### ISSUE THREAD

**Issue by patrickcerny** [AlpsBTE/alpsbte-website#3]
We should start with some baisc tasks, such as implementing basic routing (i suggest lazy loading because of all the images that need to be loaded)!

**Comment by Georg-code** [comment]
How should we implement lazy loading? The "React" way isn't posible cause of nx. Any Ideas? @patrickcerny

**Comment by b3h3m0th** [comment]
[This](https://www.typescriptlang.org/play?#code/C4TwDgpgBAkgdgS2AghgGygXigbwFBRRwoC2EAXFAM7ABOCcA5gNwFQDGA9gK5zCVxuJAEYRarAL6s8oSFACiAD2AQ4AEwhqsuNsTKUa9Jq0Jde-IkNHi8EqADJcUANoBrCCAN0GjALqUUOBAoKTw8LjgaKBUaSiUVdU1tfEI9CigAIjSMgBo2Mz5KADYSvMIqTjIAeWAACzEABVpOSFpQSgzOADMAQSCAFXAIXNtWIA) should do with React:

**Comment by Georg-code** [comment]
Yes, but we aren't importing the library from a direct path, rather by @alpsbte/shared/components and react dosn't understand that somehow

**Comment by b3h3m0th** [comment]
On what branch have you started implementing it? Can I take a look at it?

**Comment by Georg-code** [comment]
I havn't yet. If you like, you can create a new one for this
