### ISSUE TITLE
Standardize styles

### ISSUE THREAD

**Issue by b3h3m0th** [AlpsBTE/alpsbte-website#41]
Styles such as

- fonts
- spacings
- colors
- etc...

should be standardized, defined and loaded one single time.

https://stackoverflow.com/questions/68923383

**Comment by patrickcerny** [comment]
@b3h3m0th can you implement it? Would be great? Just use generic styles at first, fine tuning would come later then 👍🏼 Only if you want tho!

**Comment by b3h3m0th** [comment]
sure
