### ISSUE TITLE
Renders Home Page on Reload on Subpage

### ISSUE THREAD

**Issue by Georg-code** [AlpsBTE/alpsbte-website#53]
If you reload for ex. the About page, your getting send back to the "/" (home) page.

**Comment by b3h3m0th** [comment]
going to fix this. probably an issue with lazy

**Comment by patrickcerny** [comment]
Found the error - the last redirecting of the router (the last Router-Block) somehow forces the page to redirect to home. If you remove that, it works perfectly fine. Probably because the empty route is used before the f. g. `aboutUs` component is loaded!

**Comment by b3h3m0th** [comment]
already fixed it
