### ISSUE TITLE
Add scrolling thingy to home page

### ISSUE THREAD

**Issue by patrickcerny** [AlpsBTE/alpsbte-website#58]
Add this scrolling thingy to the home Page! Only to desktop tho!
![image](https://user-images.githubusercontent.com/47179765/130783366-6f321da1-92c8-4db9-a1c4-b9dafa7301b7.png)

**Comment by b3h3m0th** [comment]
unnecessary in my opinion

**Comment by NApartas** [comment]
It is not unnecessary. Many people will not scroll because the picture at the top covers the whole page.

**Comment by b3h3m0th** [comment]
I've had different experiences. I feel like this has become a weird trend. But well its literally 3 lines of code. we can change it easily. Going to do this tomorrow.
