### ISSUE TITLE
"Not Found" Page - Implement and rederict to it

### ISSUE THREAD

**Issue by patrickcerny** [AlpsBTE/alpsbte-website#59]
Currently, we have a error page - it's unused tho! Please implement it accordingly to the style after talking to @Cinnazeyy and edit the routing config! I think it would be a great task for @Georg-code or @jokil123, you guys can talk w/ eachother who wants to implement it!

**Comment by Georg-code** [comment]
Ok, we'll do it. @jokil123 Do you have time to talk later? 17:30?

**Comment by b3h3m0th** [comment]
I have already resolved this with #76 I believe
