### ISSUE TITLE
Storybook Setup

### ISSUE THREAD

**Issue by b3h3m0th** [AlpsBTE/alpsbte-website#6]
Storybook setup fixen. Des isch momentan fürd Tonne

**Comment by patrickcerny** [comment]
please erläutern bro

**Comment by b3h3m0th** [comment]
Jo na isxh ned tragisch. Es gibt nur paar Probleme mit tsconfigs und so. Kann i ma sus o aschaua

**Comment by patrickcerny** [comment]
Jo aber wie moansch du des probleme i woas ned was moansch genau? isch was falsch ufgsetzt? s isch eig alles fresh out of the box vu NX

**Comment by b3h3m0th** [comment]
hosch [do](https://github.com/AlpsBTE/alpsbte-website/blob/7e4a4636e1b5470e65af6e19277ab1e1044aa0cf/libs/shared/components/.storybook/tsconfig.json#L1) du kua fehler?

**Comment by patrickcerny** [comment]
jaein, also es wirft glob an fehler, aber es compiled also 🤷🏼‍♂️ Min IDE hot halt glob iwelle linting errors

**Comment by b3h3m0th** [comment]
jo richtig und des sött ned si
