### ISSUE TITLE
Implement Loading Page

### ISSUE THREAD

**Issue by patrickcerny** [AlpsBTE/alpsbte-website#68]
currently between loading pages, we dont have a page to display. Implement accordingly

**Comment by John8790909** [comment]
You could use Material-Uis circular progress https://material-ui.com/components/progress/ to make a simple loading page.

**Comment by Georg-code** [comment]
I don't think we need material UI for that. I will probably make our own spinner.

**Comment by John8790909** [comment]
Using css and svgs?

**Comment by patrickcerny** [comment]
Probably, i css loader is not the hardest thing to animate and more JS and packages would just make the bundle size bigger and the page slower.

**Comment by Georg-code** [comment]
Look at https://loading.io/css/ as inspiration. Very basic todo
