### ISSUE TITLE
language support front (+ backend)

### ISSUE THREAD

**Issue by jokil123** [AlpsBTE/alpsbte-website#69]

**Comment by b3h3m0th** [comment]
frontend basically done

**Comment by patrickcerny** [comment]
@b3h3m0th am i assigned to the backend?

**Comment by b3h3m0th** [comment]
I don't think so.
I'm actually thinking about just leaving away the backend for the language system completely because it works really really well with just reading the json and its way faster.

**Comment by patrickcerny** [comment]
so is the issue ready to close?
