### ISSUE TITLE
Docker Setup

### ISSUE THREAD

**Issue by b3h3m0th** [AlpsBTE/alpsbte-website#8]

**Comment by patrickcerny** [comment]
@b3h3m0th any new updates - is Docker even needed?

**Comment by b3h3m0th** [comment]
wh eh ned aba wär nice to have

**Comment by patrickcerny** [comment]
Also kann ich das Issue closen oder machtst dus noch fertig? + Dann brauchen wir 2 verschíedene Docker files für Back / Frontend 👍🏼
