### ISSUE TITLE
Fix Mobile Homepage

### ISSUE THREAD

**Issue by NApartas** [AlpsBTE/alpsbte-website#83]
Right now every page is working perfectly in mobile except the Homepage. You can scroll sideways.

**Comment by b3h3m0th** [comment]
I already fixed this in #78. Which means that this issue is going to resolved on master as soon as #78 is merged.

**Comment by NApartas** [comment]
Alright. Once the architecture is changed so that wip things will be shown real-time on Dev. Alps-BTE.com this won't happen again ;)

**Comment by b3h3m0th** [comment]
If we change it that dev.alps-bte.com will build master branch you will still only see merged things. Progress on other branches will alwys only be visible locally.

**Comment by NApartas** [comment]
Sure, however faster than previously
